project_name: "nexusflow_churn_prediction"
primary_key: "user_id"

target:
  target_column: "churn_risk"
  target_table: "users.csv"

# Dataset configurations with different transformer types
datasets:
  - name: "users.csv"
    transformer_type: "ft_transformer"  # Feature Tokenizer Transformer for tabular data
    complexity: "medium"
    context_weight: 1.0
    categorical_columns: ["region", "subscription_tier"]
    numerical_columns: ["age", "income", "account_tenure_months", "num_products", "support_tickets"]
  
  - name: "transactions.csv"
    transformer_type: "standard"  # Standard transformer with FlashAttention
    complexity: "medium"
    context_weight: 0.8
    categorical_columns: ["payment_method", "transaction_category"]
    numerical_columns: ["transaction_amount", "transaction_frequency", "days_since_last_transaction", "merchant_rating"]

# Advanced architecture configuration
architecture:
  global_embed_dim: 128
  refinement_iterations: 4
  use_moe: true              # Enable Mixture of Experts
  num_experts: 6             # Number of expert networks
  use_flash_attn: true       # Enable FlashAttention optimization
  top_k_contexts: 3          # Limit cross-attention to top-3 most relevant contexts

# Training configuration
training:
  batch_size: 32
  epochs: 15
  optimizer:
    name: "adam"
    lr: 0.001
    weight_decay: 0.0001
  
  # Advanced preprocessing
  use_advanced_preprocessing: true
  auto_detect_types: true
  
  # Training optimizations
  early_stopping: true
  patience: 5
  gradient_clipping: 1.0
  
  split_config:
    test_size: 0.2
    validation_size: 0.2
    randomize: true

# MLOps configuration
mlops:
  logging_provider: "stdout"
  experiment_name: "churn_prediction_demo"
  log_attention_patterns: false